import {records,check,validReason,simulatedSuggestions} from './data.js';
const $=id=>document.getElementById(id);
let snapshot=null;
$('records').innerHTML=records.map(r=>`<tr><td><strong>${r.id}</strong><small>${r.item}</small></td><td>${r.cartons}</td><td>${r.packing??'Desconocido'}</td><td>${r.requested}</td></tr>`).join('');
function invalidate(){snapshot=null;$('download').disabled=true;$('print').disabled=true;$('artifact-state').textContent='Sin registro vigente';$('arithmetic-state').textContent='Vuelve a comprobar tras editar';$('export-status').textContent='Hay cambios sin guardar: vuelve a comprobar y guarda el cambio.';}
for(const id of ['reason','assistance']) $(id).addEventListener('input',invalidate);
$('followup').addEventListener('input',()=>{if(snapshot)delete snapshot.changedScenario;$('download').disabled=true;$('print').disabled=true;$('changed-result').textContent='';$('export-status').textContent='Guarda la explicación del cambio para descargar.';});
document.querySelectorAll('[name="route"]').forEach(el=>el.addEventListener('change',()=>{invalidate();$('route-note').textContent=el.value==='existing'?'Registro inventado ya disponible: usa la tabla como evidencia inicial. No subas documentos reales.':'Tarea ficticia alternativa: revisa esta tabla como ejercicio de práctica. No hay trabajo para una empresa.';}));
$('form').addEventListener('submit',event=>{event.preventDefault();$('reason-error').textContent=validReason($('reason').value)?'':'Escribe entre 30 y 1200 caracteres para explicar tu decisión.';$('assistance-error').textContent=$('assistance').value?'':'Declara la ayuda usada o elige «Prefiero no declarar».';if(!validReason($('reason').value)||!$('assistance').value)return;
 const facts=records.map(check);snapshot={version:'FIRST-PROOF-v1',fictional:true,route:document.querySelector('[name="route"]:checked').value,source:'INVENTARIO-DEMO-v1',records,facts,explanation:$('reason').value.trim(),assistance:$('assistance').value,ai:{mode:'SIMULATED_PRERECORDED',suggestions:simulatedSuggestions},states:{artifactExists:true,arithmetic:'Calculated; DEMO-04 remains unknown',personReasoning:'NOT_HUMAN_VERIFIED',employerAcceptance:'NOT_ESTABLISHED'}};
 $('facts').replaceChildren(...facts.map(f=>{const p=document.createElement('p');p.className='fact';p.textContent=`${f.id} · ${f.status}${f.units===null?'':`: ${f.units} unidades; diferencia ${f.difference>0?'+':''}${f.difference}`}`;return p;}));$('suggestions').replaceChildren(...simulatedSuggestions.map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));$('results').hidden=false;$('artifact-state').textContent='Explicación registrada; cambio pendiente';$('arithmetic-state').textContent='3 filas calculadas; DEMO-04 indeterminada';$('export-status').textContent='Guarda tu explicación del cambio para descargar.';$('changed-result').textContent='';$('download').disabled=true;$('print').disabled=true;
});
$('record-followup').addEventListener('click',()=>{if(!snapshot){$('followup-error').textContent='Vuelve a comprobar los números para guardar los cambios.';return;}if(!validReason($('followup').value)){$('followup-error').textContent='Escribe entre 30 y 1200 caracteres.';return;}$('followup-error').textContent='';snapshot.changedScenario={record:{...records[0],cartons:4},fact:check({...records[0],cartons:4}),explanation:$('followup').value.trim(),humanVerification:false};$('changed-result').textContent='DEMO-01 ahora suma 48 unidades y coincide. Tu explicación está registrada, sin verificación humana.';$('artifact-state').textContent='Registro listo para descargar';$('export-status').textContent='Copia local lista. No se enviará a nadie.';$('download').disabled=false;$('print').disabled=false;});
$('download').addEventListener('click',()=>{if(!snapshot?.changedScenario)return;const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='primera-prueba-inventario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('print').addEventListener('click',()=>window.print());
$('reset').addEventListener('click',()=>{ $('form').reset();$('followup').value='';$('results').hidden=true;$('route-note').textContent='Registro inventado ya disponible: usa la tabla como evidencia inicial. No subas documentos reales.';for(const id of ['reason-error','assistance-error','followup-error','changed-result'])$(id).textContent='';invalidate();$('artifact-state').textContent='Aún no guardado';$('arithmetic-state').textContent='Pendiente de comprobar';$('export-status').textContent='Completa la explicación y el cambio para descargar.';});
